### PR TITLE
Modified specieset to maintain the original order

### PR DESCRIPTION
**Pull request by ftherrien**
For defect calculations, the order in the structure is important, the previous function was losing that order by placing the species in alphabetical order.

### CODE REVIEW

**Comment by mdavezac** [comment]
The whole point of the function is to return a list of species with a reproducible order, even if the order of the atoms in the structure changes. If I remember well, anything else can lead to issues in VASP, when looking at older poscars where atomic types are not explicit.

Why is the order of atoms important in your case? Would it be possible to add a label to the relevant atoms rather than making them come first?

**Comment by mdavezac** [comment]
@ftherrien, @vstevano, I'm not sure what you guys have decided here. If you think this should be merged, please do so.

However, @ftherrien, before merging, please correct the magmon tests for the new species order. Currently, they fail (try running `cd build; ./localpython.sh -m python ../vasp/tests`).
I know travis says things pass, but that's a problem with travis I have to look into.

**Comment by ftherrien** [comment]
@mdavezac, we tried running `cd build; ./localpython.sh -m python ../vasp/tests`, but it fails before it does any test....

We first got the following:

> Traceback (most recent call last):
>   File "/home/felixt/.conda-envs/easypylada/lib/python2.7/runpy.py", line 163, in _run_module_as_main
>     mod_name, _Error)
>   File "/home/felixt/.conda-envs/easypylada/lib/python2.7/runpy.py", line 111, in _get_module_details
>     __import__(mod_name)  # Do not catch exceptions initializing package
>   File "python/__init__.py", line 127, in <module>
>     logger = __setup_logger()
>   File "python/__init__.py", line 109, in __setup_logger
>     logging_level = environ.get('LADA_LOGGING_LEVEL', local_dict['logging_level'])
> KeyError: 'logging_level'

It seems like the build/python module thinks it is somewhere else... It's looking in the wrong directory for config/logging.py. We changed the path so that it find it (logging.py) but it is now trying to import pylada modules (error, crystal, ...) from the build directory which fails.... 

How should we proceed? Did you change anything in your pylada to make testing work?

We are trying to decide what to do with specieset() but we need to be able to run the tests first.

**Comment by ftherrien** [comment]
We all agreed that keeping the original order was better. I modified the tests so that they work with the new specieset. You can accept the request if you agree. (or you can wait after  #40)

**Pull request merged**
