### PR TITLE
Python 2 is still alive!

### LINKED ISSUE #44: collections.abc in python2
A lot of us are still using python 2 (even though life is short...) and abc is still in collections for that version of the standard library such that import pylada fails with:

> from collections.abc import MutableSequence
> ImportError: No module named abc

This is after 09ce32200ddf94620a8cdf96b98144282a460e37. Maybe do something like:

```
try:
    from collections.abc import MutableSequence
except ImportError:
    from collections import MutableSequence
```

That would get rid of the deprecation warning.

### PR DESCRIPTION
**Pull request by ftherrien**
This is my suggestion to fix #44. That way the depreciation warning does not show up and pylada still works in python 2.

### CODE REVIEW

**Comment by ftherrien** [comment]
Is this better?

Do you know why the tests are failing?

**Comment by ftherrien** [comment]
Found it! I will add new commit and see if it still fails

**Comment by ftherrien** [comment]
@mdavezac the tests seem to be failing because of a fixture issue in espresso/tests/bdd/test_restart.py. Rewritting the function this way solves the issue, should I create a specific pull request for that?

```
 from pylada.espresso.tests.fixtures import diamond_structure as structure
 
 @given("a distorted diamond structure")
 def distorted_diamond(structure):
     from numpy.random import random
     #structure = diamond_structure()    
```

**Comment by mdavezac** [comment]
Let me take a look this WE

**Comment by mdavezac** [comment]
@ftherrien, I think it should pass now. It's was really just some iffy code that used to be okay, but  that pytest rejects now.

I've also simplified (... i think ...) some of the code in tools/makeclass.py, compared to what you were proposing.

**Comment by mdavezac** [comment]
@ftherrien, can you confirm this works on your end? Then we can merge.

**Comment by ftherrien** [comment]
@mdavezac everything seems to work for me

**Pull request merged**
